apiVersion: v1
kind: Service
metadata:
  name: {{ include "users-crud.fullname" . }}-users
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "users-crud.labels" . | nindent 4 }}-users
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    {{- include "users-crud.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "users-crud.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "users-crud.labels" . | nindent 4 }}-auth
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    {{- include "users-crud.selectorLabels" . | nindent 4 }}