{
 "title": "Online Shop",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alive Pods Count By Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"miniapp\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Stock Changes Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (service) (rate(process_stock_changes_errors_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Courier Reserve Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (service) (rate(process_cour_reserve_errors_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Payments Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (service) (rate(process_payment_errors_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nginx Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(nginx_ingress_controller_nginx_process_requests_total[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(nginx_ingress_controller_requests{status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_requests{service=\"miniapp-order\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Billing Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_requests{service=\"miniapp-billing\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stock Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_requests{service=\"miniapp-stock\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_requests{service=\"miniapp-auth\"}[1m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Notifications Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_requests{service=\"miniapp-notifications\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delivery Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_requests{service=\"miniapp-delivery\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_requests{service=\"miniapp-users\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (datname, instance) (pg_database_size_bytes{datname=\"miniapp\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(pg_replication_lag_seconds) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx And Rollback Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum by (datname, datid) (rate(pg_stat_database_xact_commit{datname=\"miniapp\"}[1m]))",
     "legendFormat": "{{datid}}"
    },
    {
     "expr": "sum by (datname, datid) (rate(pg_stat_database_xact_rollback{datname=\"miniapp\"}[1m]))",
     "legendFormat": "{{datid}}"
    }
   ]
  },
  {
   "title": "Read DB Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum by (service) (rate(db_read_errors_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write DB Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum by (service) (rate(db_write_errors_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Start TX Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "sum by (service) (rate(db_start_tx_errors_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Commit TX Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum by (service) (rate(db_commit_tx_errors_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Data Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(redis_master_last_io_seconds_ago) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keys Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    { "expr": "sum(redis_db_keys) by (db)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Topics Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "sum(kafka_log_log_logendoffset-kafka_log_log_logstartoffset{topic!~\"__.*\"}) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unread Messages By Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "max(kafka_client_lag) by (topic,partition)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"miniapp-.+\"}[1m])) * 100",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_usage_bytes{pod=~\"miniapp-.+\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}