apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "miniapp.fullname" . }}-cm-users
  namespace: {{ .Release.Namespace }}
data:
  app-config: |
    log-file = "/var/log/users.log"
    log-level = "info"
    listen-port = "8000"
    auth-addr = "http://{{ include "miniapp.fullname" . }}-auth:{{ .Values.service.port }}{{ .Values.auth.path }}"
    base-path = "{{ .Values.users.path }}"

    [db-config]
    host = "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
    user = "postgres"
    database = "miniapp"
    sslmode = "disable"
    port = 5432

    [redis-config]
    host = "{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local"
    port = 6379

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "miniapp.fullname" . }}-cm-auth
  namespace: {{ .Release.Namespace }}
data:
  app-config: |
    log-file = "/var/log/auth-service.log"
    log-level = "info"
    listen-port = "8000"
    base-path = "{{ .Values.auth.path }}"
    billing-addr = "http://{{ include "miniapp.fullname" . }}-billing:{{ .Values.service.port }}{{ .Values.billing.path }}"

    [db-config]
    host = "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
    user = "postgres"
    database = "miniapp"
    sslmode = "disable"
    port = 5432

    [redis-config]
    host = "{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local"
    port = 6379

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "miniapp.fullname" . }}-cm-billing
  namespace: {{ .Release.Namespace }}
data:
  app-config: |
    log-file = "/var/log/billing-service.log"
    log-level = "info"
    listen-port = "8000"
    base-path = "{{ .Values.billing.path }}"
    auth-addr = "http://{{ include "miniapp.fullname" . }}-auth:{{ .Values.service.port }}{{ .Values.auth.path }}"

    [db-config]
    host = "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
    user = "postgres"
    database = "miniapp"
    sslmode = "disable"
    port = 5432

    [redis-config]
    host = "{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local"
    port = 6379

    [consumer-config]
    topics = ["payments"]
    group-id = "payments"
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]

    [producer-config]
    topics = ["payments_status"]
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]
