apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "miniapp.fullname" . }}-cm-users
  namespace: {{ .Release.Namespace }}
data:
  app-config: |
    log-file = "/var/log/users.log"
    log-level = "info"
    listen-port = "8000"
    auth-addr = "http://{{ include "miniapp.fullname" . }}-auth:{{ .Values.service.port }}{{ .Values.auth.path }}"
    base-path = "{{ .Values.users.path }}"

    [db-config]
    host = "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
    user = "postgres"
    database = "miniapp"
    sslmode = "disable"
    port = 5432

    [redis-config]
    host = "{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local"
    port = 6379

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "miniapp.fullname" . }}-cm-auth
  namespace: {{ .Release.Namespace }}
data:
  app-config: |
    log-file = "/var/log/auth-service.log"
    log-level = "info"
    listen-port = "8000"
    base-path = "{{ .Values.auth.path }}"
    billing-addr = "http://{{ include "miniapp.fullname" . }}-billing:{{ .Values.service.port }}{{ .Values.billing.path }}"

    [db-config]
    host = "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
    user = "postgres"
    database = "miniapp"
    sslmode = "disable"
    port = 5432

    [redis-config]
    host = "{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local"
    port = 6379

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "miniapp.fullname" . }}-cm-billing
  namespace: {{ .Release.Namespace }}
data:
  app-config: |
    log-file = "/var/log/billing.log"
    log-level = "info"
    listen-port = "8000"
    base-path = "{{ .Values.billing.path }}"
    auth-addr = "http://{{ include "miniapp.fullname" . }}-auth:{{ .Values.service.port }}{{ .Values.auth.path }}"

    [db-config]
    host = "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
    user = "postgres"
    database = "miniapp"
    sslmode = "disable"
    port = 5432

    [redis-config]
    host = "{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local"
    port = 6379

    [consumer-config]
    topic = "payments"
    group-id = "payments"
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]

    [producer-config]
    topic = "payments_status"
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "miniapp.fullname" . }}-cm-stock
  namespace: {{ .Release.Namespace }}
data:
  app-config: |
    log-file = "/var/log/stock.log"
    log-level = "info"
    listen-port = "8000"
    auth-addr = "http://{{ include "miniapp.fullname" . }}-auth:{{ .Values.service.port }}{{ .Values.auth.path }}"
    base-path = "{{ .Values.stock.path }}"

    [db-config]
    host = "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
    user = "postgres"
    database = "miniapp"
    sslmode = "disable"
    port = 5432

    [redis-config]
    host = "{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local"
    port = 6379

    [consumer-config]
    topic = "stock_changes"
    group-id = "stock_changes"
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]

    [producer-config]
    topic = "stock_changes_status"
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "miniapp.fullname" . }}-cm-order
  namespace: {{ .Release.Namespace }}
data:
  app-config: |
    log-file = "/var/log/order.log"
    log-level = "info"
    listen-port = "8000"
    auth-addr = "http://{{ include "miniapp.fullname" . }}-auth:{{ .Values.service.port }}{{ .Values.auth.path }}"
    base-path = "{{ .Values.order.path }}"

    [db-config]
    host = "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
    user = "postgres"
    database = "miniapp"
    sslmode = "disable"
    port = 5432

    [redis-config]
    host = "{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local"
    port = 6379

    [payments-consumer-config]
    topic = "payments_status"
    group-id = "payments_status"
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]

    [payments-producer-config]
    topic = "payments"
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]

    [stock-consumer-config]
    topic = "stock_changes_status"
    group-id = "stock_changes_status"
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]

    [stock-producer-config]
    topic = "stock_changes"
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]

    [notifications-producer-config]
    topic = "notifications"
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]

    [cour-reserve-consumer-config]
    topic = "cour_reserve_status"
    group-id = "cour_reserve_status"
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]

    [cour-reserve-producer-config]
    topic = "cour_reserve"
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "miniapp.fullname" . }}-cm-notifications
  namespace: {{ .Release.Namespace }}
data:
  app-config: |
    log-file = "/var/log/notifications.log"
    log-level = "info"
    listen-port = "8000"
    auth-addr = "http://{{ include "miniapp.fullname" . }}-auth:{{ .Values.service.port }}{{ .Values.auth.path }}"
    base-path = "{{ .Values.notifications.path }}"

    [db-config]
    host = "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
    user = "postgres"
    database = "miniapp"
    sslmode = "disable"
    port = 5432

    [redis-config]
    host = "{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local"
    port = 6379

    [consumer-config]
    topic = "notifications"
    group-id = "notifications"
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "miniapp.fullname" . }}-cm-delivery
  namespace: {{ .Release.Namespace }}
data:
  app-config: |
    log-file = "/var/log/delivery.log"
    log-level = "info"
    listen-port = "8000"
    auth-addr = "http://{{ include "miniapp.fullname" . }}-auth:{{ .Values.service.port }}{{ .Values.auth.path }}"
    base-path = "{{ .Values.delivery.path }}"

    [db-config]
    host = "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
    user = "postgres"
    database = "miniapp"
    sslmode = "disable"
    port = 5432

    [redis-config]
    host = "{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local"
    port = 6379

    [cour-reserve-consumer-config]
    topic = "cour_reserve"
    group-id = "cour_reserve"
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]

    [cour-reserve-producer-config]
    topic = "cour_reserve_status"
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]

    [notifications-producer-config]
    topic = "notifications"
    version = "4.0.0"
    brokers = [{{- $rn := .Release.Name -}}
    {{- $ns := .Release.Namespace -}}
    {{- $port := int .Values.kafka.service.ports.client -}}
    {{- printf "\"%s-kafka-controller-headless.%s.svc.cluster.local:%d\"" $rn $ns $port -}}]