apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-password: UXdlcnR5MTIzNCFA
  replication-password: UXdlcnR5MTIzNCFA

---

apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  redis-password: UXdlcnR5MTIzNCFA

---

apiVersion: v1
kind: Secret
metadata:
  name: rsa-cert
type: Opaque
data:
  private-key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktZd2dnU2lBZ0VBQW9JQkFRQ1NhN1JzcXFXbSt6Z2QKZGRocWJaNzZIcnM4RnhhSzIrRWdo
    TkpFTTl3Mko5WE1vZWw0QVc5SlBydVpzeHdMYkNXd0VzMDJXdGJ5MWwxZAorZXl0R0pLYStFOWV6
    Y2pJc3dURFVwTU5ia1d0RUM4MVNHVzZ6SkVCTGowRE1vOThKMVhzWmVZQm5nSk1Td29tCnd4UHc3
    dGNKU1FZQWF2UkdDZ2pkWERFQ0o2VHBZMkpHd1RZZU8xbUwvVTJqNitvbnFFL0pLZm1GdzB0UGFt
    TG4KSWN4bk5pMHdRUGZXcklYMVBKUVZGRW4yOWtUQWNGL1FHVlcvU2FOa1FhaThYUVl1NHNGWVJ5
    c1oyU3NNRW1MSAptNmRuaHZycG44YmxHVGszc2tEKytlS1ZWUDhCbFRQM1lmeHpYNnhtd3o3S1k5
    WGFoN3FGSVhoYytZZXF4RjF0CnVEcmw1NU85QWdNQkFBRUNnZ0VBTHI5c2IzVmNSaC9YSHJETlU4
    MkVBRjluY0J2KytuNlJOZ3l5QlV4NWRtRHAKaGRmNzduQ20wei9RTFpaZDBkZkpnSm5BSXlhRmtp
    cVd6TFpLdGtrdUpZUTU4dzdJbUN0dnpkekRUbnB5akhxcQpWOXl4Zmg1cC9YS0IwRStJT0I5bTgz
    N2xISWNTUE1HSWtDK2dZa0FmTDd1OHlzMWJDREdUK3ZqQVBPdmpYdy84CktoVHhxcS92M09KV3Yw
    MHNacEtOTU40bi8zL1JEanlZUjI2MWNmazdBQ3V5clFVcU1MeUc5aWdyLzJNUmdVZzUKMHZHYUU1
    Y2lLeVp6SEdOVTdCS0JpNXhBMFAwOVRLdXJhZWFSeFV5Nm9halNWNFlGOUlXQTQwU3pJaGhtYmJ5
    cgpsZ2R4dm44N1F1RGdVOC9JNDVPZ3RWUnloV0g3Q3JPTTJLYnVaczk4RVFLQmdRRE5xa3JGUGFI
    WDFSMTBGQzR3CndoSENndEVDMVU5K3hlems0bkhIMXE4bG5FNmNqZHVEYmpQaEU3UUdwUWVqaVl2
    Y0NySEx6WWMzZGFHNE1FK2oKNDhRQUkwZWFTTUNZQ1paTnVqVXc2WHQ4aU9KVCtMWWF6TktYc3kr
    R0xIUDNPNWEzSEdoY2dTeGdycWJRc2ZhTwpVcUVPd3g4QXhBZ2JhZkRJdlBjckIzaC9Ud0tCZ1FD
    MlFZVTVQUG9VeEJ3bHNNYWlmeGtmd2FJRTNIL3QxdVE3CndTb0RGb25uczVQRmhiTFMvQU9RZUhT
    TDJtS3p3ZzNVaDlpZjJyNUtDZFBKanBFMXF4aTNKZ3pHSlNYb0YxNnIKT2hzeTNEalA0WTNoVTFt
    MFZlS3RwR1pNM0tBaGZUdVlxeXh0SDZjYzZGejlodnFPeXp3ZGJuVGpiOGQ2R0RsdApydjY4bWpD
    Wk13S0JnRHQyTk0vNkZjVFZOUUxPb3R3dC8veUEzZlUzdnhna0dXM0RtcW53aEFzWHVoTEJZT29L
    Ci9xemdpWGd5VnBjTnVZWVJBWDZ2R1owTFFZcURUVU5SSXVYM1RVaHFLR1RNd013UVBqaTZDSjNr
    NWFycGlaME8KQXdVaEpXaGhpZFc5UU1JSVVKUU9OTXB2TklPNk1GTE55UXIvbHdNZHFrcGl3dDhH
    NDE5cGRZazVBb0dBQmM2QQptQnBCUFhnaURYRmNZc0Q1NC9FZllGaEdHeVhGajhIUHZObHkrMWJW
    Vm0yMEROVEtxRWV1THVaK1RvdllOUFUvCkNaakdoMFZZNGdzUXhVejJOSitadUpabVpzYVgxWXk4
    WVJwekZPeHl3TU1QRUpmTDZReGIxZ2NSY3YreWJtTEYKdjVSS2xya3dmVU5YcUVVQlhVNnZtcTl0
    QTQ3U0JaU1Z1UnlRZjlFQ2dZQjM1ZEZVWk80SUxGbjV5WXpBcExYUgpNVU0xV0ZRbkdxeVpzMlJz
    QUo4MFhicjJibThBNjA4c1pLZTl3eU5CV1dweDd4OHFnYzlMZ05pUDd6SzdxQWYrCnNHNXB5NVkv
    QjIzUVNjZnZoMHlPUVI5VXYxVHZGZTBJbEdQbk9pZm1odi9lcmNiNjUzYzVzOEFnS2J3ZzhLalgK
    bklNSTgvQ2dpTTJ5ZXdsNUFxOUZPQT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K

  public-key: |
    LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FR
    OEFNSUlCQ2dLQ0FRRUFrbXUwYktxbHB2czRIWFhZYW0yZQoraDY3UEJjV2l0dmhJSVRTUkRQY05p
    ZlZ6S0hwZUFGdlNUNjdtYk1jQzJ3bHNCTE5ObHJXOHRaZFhmbnNyUmlTCm12aFBYczNJeUxNRXcx
    S1REVzVGclJBdk5VaGx1c3lSQVM0OUF6S1BmQ2RWN0dYbUFaNENURXNLSnNNVDhPN1gKQ1VrR0FH
    cjBSZ29JM1Z3eEFpZWs2V05pUnNFMkhqdFppLzFObyt2cUo2aFB5U241aGNOTFQycGk1eUhNWnpZ
    dApNRUQzMXF5RjlUeVVGUlJKOXZaRXdIQmYwQmxWdjBtalpFR292RjBHTHVMQldFY3JHZGtyREJK
    aXg1dW5aNGI2CjZaL0c1Ums1TjdKQS92bmlsVlQvQVpVejkySDhjMStzWnNNK3ltUFYyb2U2aFNG
    NFhQbUhxc1JkYmJnNjVlZVQKdlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==