definitions:
  types.HTTPError:
    properties:
      error:
        type: string
    type: object
  types.Item:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
    type: object
info:
  contact: {}
  description: This is a stock service API.
  license:
    name: Apache 2.0
  termsOfService: http://swagger.io/terms/
  title: Stock API
  version: "1.0"
paths:
  /add_item:
    post:
      consumes:
      - application/json
      description: add item
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Item'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.HTTPError'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/types.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.HTTPError'
      summary: add item
      tags:
      - stock
  /stock_change:
    post:
      consumes:
      - application/json
      description: stock_change
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.HTTPError'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/types.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.HTTPError'
      summary: stock_change
      tags:
      - stock
  /update_item:
    post:
      consumes:
      - application/json
      description: update_item
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/types.HTTPError'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/types.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/types.HTTPError'
      summary: update_item
      tags:
      - stock
swagger: "2.0"
